name: Android CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    
    # هنا نطلب الإصدار 8.7 تحديداً ليتوافق مع مشروعك
    - name: Setup Gradle Wrapper
      run: gradle wrapper --gradle-version 8.7
      
    - name: Build with Gradle
      run: ./gradlew assembleDebug
